### ISSUE TITLE
Undefined Index Updated from D7 Price per Role

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/uc_price_per_role#1] opened 2020-10-28 17:38 UTC
I am getting the following:

Notice: Undefined variable: display_price in uc_price_per_role_form_alter() (line 220 of /home/tbwdev/public_html/asibd/modules/uc_price_per_role/uc_price_per_role.module).

And it seems to be causing the wrong role prices to be displayed on products.  The prices are correct on the product's edit page.  Just not displaying correctly.  And when I went in to edit, I resaved and the display price changed.  But it still didn't seem to be honoring the users role.

BTW, you have no idea how happy I was to see this module pop up :)

**Comment by bugfolder** [comment] 2020-10-29 03:13
Hi Sam,
Is this a new install, or are you upgrading from an existing Drupal site?

**Comment by samgreco** [comment] 2020-11-02 16:11
Upgrading from an existing site.  With some 1200 products.  This is a test run.  I am planning either a migration to a completely different platform, or an update to Backdrop.  I have always preferred Ubercart to Commerce.  So was hoping to have a path to BD.  Getting close.

**Comment by bugfolder** [comment] 2020-11-02 16:32
Ok. I’ll work with you to try to resolve this, but my computer’s in the shop for a few weeks, so it won’t be till mid-nov till I can start exploring/diagnostics. I’ll ping when I can.

**Comment by bugfolder** [comment] 2020-11-14 21:54
Hey, I'm back up and running (swollen Mac battery replaced) and started looking into the logic that leads to the error you cited.

Can you tell me what the Attribute settings are on your installation at /admin/store/settings/products? (I suspect none are set, even though they're radio buttons.)

**Comment by bugfolder** [comment] 2020-11-18 20:59
So, @samgreco, at least part of the issue is a problem in uc_attributes (not uc_price_per_role). Would you please set the attribute settings at /admin/store/settings/products and look again? Or if you are re-running the import from D7, please apply [this patch](https://github.com/backdrop-contrib/ubercart/commit/011f42a0958afe5e51033d8fbb895228360b6dca) to your Backdrop installation before upgrading, and let me know if that fixes things (at the least, it should eliminate the warning).

**Comment by samgreco** [comment] 2020-12-16 18:28
My apologies!  I haven't been getting notifications so didn't know you replied.  I'll take a look and get back to you shortly.

**Comment by samgreco** [comment] 2021-01-20 22:35
Sorry for the long wait.  But yes, the update fixed the issue.  Price per Role updates correctly now on a fresh migration (same sites involved).

**Comment by bugfolder** [comment] 2021-01-20 22:36
Great! Closing the issue.

**Closed as completed by bugfolder** 2021-01-20 22:36 UTC
