### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/uc_price_per_role#5] opened 2022-05-19 19:03 UTC
One thing I've noticed is that the page seems to cache the price fairly aggressively. For example, if I load the page with special pricing when logged in, and then open a private window and view the same page, the special pricing shows up for the anonymous view, too. Or if I load the page in a private window, clear caches on a separate tab, reload the private window: regular pricing shows up for the anonymous user -- but it also shows up when I view the page as a user with the role that should get special pricing.

**Comment by bugfolder** [comment] 2022-05-19 19:43
This may be a Backdrop thing, because I've noticed a similar behavior with my [User Time Zone Tokens](https://backdropcms.org/project/utz_tokens) module. The "use the user's time zone" setting is basically unusable on Backdrop (though it worked on Drupal) because everyone sees the time zone of the last user for whom that page rendered.

**Comment by laryn** [comment] 2022-05-19 21:57
I wonder if it's due to Entity Cache being in core. I'll throw the question out on Zulip:

 - https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Caching/near/282997225

**Comment by bugfolder** [comment] 2022-05-19 22:21
Seems to be; clearing all caches makes the next page load work properly, and just clearing the node's row in table `cache_entity_node` does, too.

**Comment by bugfolder** [comment] 2022-05-19 22:37
The "load from cache" happens in `entity_controller.inc` at line 310 after `// Try to load entities from the persistent cache.` If I hack this bit to disable the cache check, I can get user-dependent node pages to render in a properly user-specific way (I'm using Token Filter's [user:name] as a quick-and-dirty check).

The Performance configuration page at `/admin/config/development/performance` offers the option to cache pages for anonymous users (or not). Seems like we should also offer the same options for caching entities, e.g., a set of checkboxes for all entity types.

So it seems like a core issue is warranted.

**Comment by laryn** [comment] 2022-05-19 22:45
I wonder if this is relevant, since the module makes use of `hook_node_load()` to change the price data (my emphasis):

[hook_node_load](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.api.php/function/hook_node_load/1):
> This hook should be used to add information that is not in the node or node revisions table, **not to replace information that is in these tables (which could interfere with the entity cache)**.

EDIT: I guess this info is not in the `node` or `node_revision` table directly, but rather in the `uc_products` table.

**Comment by bugfolder** [comment] 2022-05-19 22:51
And I just confirmed that (a) the problem exists on a test site that uses `uc_price_per_role`, and (b) hard-coded disabling entity caching on the site fixes the problem.

**Comment by bugfolder** [comment] 2022-05-20 14:43
@argiepiano [suggests on Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Caching/near/283077161):

> While that feature gets developed and added, perhaps [module maintainers] can use hook_entity_info_alter to disable caching for nodes in that particular module?

Great suggestion, that should work.

**Comment by bugfolder** [comment] 2022-05-20 17:41
PR is in place, it works for me. If anyone else could verify, I'll merge this in and do a release.

**Comment by laryn** [comment] 2022-05-20 17:58
@bugfolder I can confirm this works. :+1: 

I don't know enough about caching to know but thought I'd ask just to be sure -- is it possible with this approach to move it up one level so the entity caching is only disabled on bundles that are uc_product types?

**Comment by bugfolder** [comment] 2022-05-20 18:16
> is it possible with this approach to move it up one level so the entity caching is only disabled on bundles that are uc_product types?

I don't think so. The code in core that decides whether to load from cache only considers the entity type, nothing deeper; it sets the `persistentCache` field in `DefaultEntityController::__construct($entityType)`, then uses that in `load()`.

It does seem a shame to have to disable caching on all nodes just to get this to work.

**Comment by argiepiano** [comment] 2022-05-20 18:28
Right. You can't selectively disable cache per bundle. HOWEVER it is possible to extend NodeStorageController and override DefaultEntityController::load(), which is where the cache_set call happens that saves the un-cached entities to the permanent cache. In that override you can selectively save the loaded node to cache depending on its type.  The new class would need to only override the load() method, by copying and pasting the one in DefaultEntityController and modifying line 368 with an if statement.

You would still need to implement hook_entity_info_alter to change the controller class for nodes.

**Comment by argiepiano** [comment] 2022-05-20 18:31
And one drawback of this is that, if `DefaultEntityController::load()` ever changes, your module would still force nodes to use your (outdated) custom controller

**Comment by bugfolder** [comment] 2022-05-27 21:00
[Issue opened in core](https://github.com/backdrop/backdrop-issues/issues/5632) to add a hook, which would permit a bit cleaner solution (if it gets accepted) because we won't have to worry about about `DefaultEntityController::load()` getting updated.

I'll merge the current PR, since it fixes the issue, but will leave this issue open, and then implement a more selective solution when there's clarity on whether the hook gets accepted.

**Comment by bugfolder** [comment] 2024-02-15 23:00
Reviewing this issue, I see that https://github.com/backdrop/backdrop-issues/issues/5632 was merged in (quite some time ago), so it's time to re-implement `hook_entity_info_alter()` and use the new `bundle cache` property for only Ubercart products.

**Comment by bugfolder** [comment] 2024-02-19 00:10
https://github.com/backdrop-contrib/uc_price_per_role/pull/10 now implements bundle-specific disabling of caching (just for Ubercart products).

**Closed as completed** 2024-03-03 14:29 UTC
